{% set version = "3.1.0" %}

package:
  name: gspread
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gspread/gspread-{{ version }}.tar.gz
  sha256: f7ce6c06250f694976c3cd4944e3b607b0810b93383839e5b67c7199ce2f0d3d

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests >=2.2.1

test:
  imports:
    - gspread

about:
  home: https://github.com/burnash/gspread
  license: MIT
  license_file: LICENSE.txt
  summary: 'Google Spreadsheets Python API'
  license_family: MIT
  dev_url: https://github.com/burnash/gspread
  doc_url: http://gspread.readthedocs.io/

extra:
  recipe-maintainers:
    - hadim
