{% set version = "4.0.0" %}

package:
  name: gspread
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gspread/gspread-{{ version }}.tar.gz
  sha256: b557a4aea9d6aa74cd411123df2f35dcde43c1faf085333efb0ede7c9f8c545d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.2.1
    - google-auth >=1.12.0
    - google-auth-oauthlib >=0.4.1

test:
  imports:
    - gspread

about:
  home: https://github.com/burnash/gspread
  license: MIT
  license_file: LICENSE.txt
  summary: Google Spreadsheets Python API
  license_family: MIT
  dev_url: https://github.com/burnash/gspread
  doc_url: http://gspread.readthedocs.io/

extra:
  recipe-maintainers:
    - akashvyom
    - burnash
