# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lEsx1V/3KQtaOmrudgvsR3vJU6tr7YTRZq2DBN4RneS2mECGIPyZxCkNug0VqZFV3vo12duexbqdmxm+C0HRcttFF8rficbXarofDhh5STEdKyaB8yFSLpykGPcSuuviSOf/x4TYC6aAxw5n7m3lCcmEALUYWJ3vvZu86v8tGa/YV30VYpSRcBeEEztBfTQUucS6qR/234W8i1u37pqrZLwmVCw6FbCjQJAQb+54mjFrJrpxWEilpfo3SyKC5M/1b8yk+PefnQkUYx0Njo1uOtAHJ1qeWF0C4jMnsFZlAnJEFGEiF1w5WiK1+WFJNR47ULTXq4opegj3vGpo3mDjUKq30hQmrcNgrP3oOtfV+ryZUhY0mAttjfLWKkjr9zUtuUggfCq9IMrKymq6irxwj6E5nteKYTg6rGMVqfe4omzOa2ocMtR2L2RO9QctYibprKV5Ybf9ufmipC75KWJ7XGAAYFrYpJSv5DlB9OazbwrgtkEz4iyGBc9wuvN0I4f4uSYQ5Z61zvv0HAN3+8wtA9j4L83+4n+n6N9Ylud583F7Y575hJnzaE6X+Ykn5dMXKnR120RdYc9PZYbMjJVysGUGCy820T9/S0ETGX6zlV7NHrTv77rVc4IWmu0i8jiGFJKlyob2fnLu4IY+XbNvAnmiDXbi/BDPFABToOrOzO4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
