travis:
  secure:
    BINSTAR_TOKEN: IvtB8ckHABOMkf2tOw7NHbu0OH/QJXtS8+m7ly4Sw+m1zyPlv6fHLfp/y5mXnbVIUf96Rt/jbKwmN/gaJLsaRXZSdIMrx7/BDdN8gQGFGmUZZqdByuZFd92DfEIXdLk91WXvpIa4XCOcYGPjuDoMPgNZOOyYS8TK+NPlLSkTVqn9MGzVgZs3Dv4faP5y9LaplZG6Zy/Rg3a5ngFNBcbfGVs8tiHKj7Axv+67W2DSIgohNdh+hwfIDNJ9nMN8UqCsFS5mY6jQTPasYRu4p79Vsgm4sSoiHM1Q2JGxAUqizefiyXySxQgESLsM1xOjMwqheAUP5BFYxiRbQY7yTnV4T2epnQEph5jTxJb6V9aWtOcBg0R4GwwsLG/YNEfstSX1U2QK3n3Je0KKSUQbuf7hcSwHfxnTkQa4tQ4MuFGJeb+t76nlt00xXNmB9qZLu+8z+Z2mcfLx2S4BBp1YzbwvPj7PTZkpJsEFnPl+lLg0zHFo+qOsFdD78qE1N1PvDtBhOzaRPfVV0oOsqoudbdvgWoIB5Igg/RZL2hOcJkohgkCnfxjTkSOL2peSuVmDu8l0myZadyIakFG9eEWHzxf/rFZRSemfuF57qfA7iRJZSTu8FeHLW1kKd52+oFuPov1Ha5JlJJf3AC2mxtH2Y65kTCEGpgak86H4VDEfHiL2TTw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
