travis:
  secure:
    BINSTAR_TOKEN: CAeaFLOA2cRRk86OGqxIratFRoS68A6JDoATcavmnk5Dd2eUlbihfwiQLjTcHwgGODdVm7KGWMifp0yo9AMHedbxe5rs0Rpf/mAH6btl2ME03WsXeUUfrv+DpQ2WRDjXit8nHTfWNs4fpcMDODtD8RhuUDTm0mNNySQXd5PgMtyy7KVuyWYMXiuAUSwJHOKNrEwFoXRQJmeM98S83QPQocS8y+8R34yZl2+aIiz6aq+reFOQ7BXy3VrUmT0pWJlCp4/zVFlVk5YdnmuPyo4xdUGEJVl1jeiB2yh9cJxLOD3CLAhxz4SyjYMIvUJLgnSqZjO4alr5wX9co61fE5n/P0JYZkKeAdEA9v8QE64cI1INBi3yDgMR+BnUNH4NpOH062ILc+QnLeshLnFwp6QY+9Fa1DX7tS0zTOsxhOkMfvOJSgAEqLGhQvBlh9/GXbVAaSRvGndHvREHQoqIHTO/3YdjMGnPvqaLN/dP0NGk7d28PCfn1MBEMnLAO5wmTk8Yk9etcyL1rmweDkm0boZRyJOieSEaCxqnfS//BGz4kvfn6lBCfKAtKFa2/txVOo+AThMd5A6r/dC3xn55a4MC+Kog93unTkjwkRzUmfxSd00MVax4piJtJKo6qwXo0cKdHM1mGGJwE6rmn+fXSWXsdupaiPTG3Y3uMSPnfb9Vt2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
